name: cinema
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  animated_notch_bottom_bar: ^1.0.3
  animations: ^2.0.11
  carousel_slider: ^5.0.0
  checkout_screen_ui: ^1.0.1
  clay_containers: ^0.3.4
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_bounceable: ^1.1.0
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.14.1
  flutter_search_bar: ^3.0.0
  flutterfire_cli: ^1.0.1-dev.4
  google_fonts: ^6.2.1
  infinite_carousel: ^1.1.1
  path_provider: ^2.1.4
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  printing: ^5.12.0
  responsive_builder: ^0.7.1
  shared_preferences: ^2.2.3
  vertical_card_pager: ^1.6.2
  video_player: ^2.9.1
  webview_flutter: ^4.8.0
  youtube_player_iframe: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/creed.jpg
    - assets/images/wolve.jpg
    - assets/images/me.jpg
    - assets/images/wolve1.jpg
    - assets/images/me1.jpg
    - assets/images/creed1.png
    - assets/images/what.jpg
    - assets/images/what1.jpg
    - assets/images/border1.png
    - assets/images/border.jpg
    - assets/images/alien.jpg
    - assets/images/alien1.png
    - assets/images/quiet.jpg
    - assets/images/quiet1.jpg
    - assets/images/rate.png
    - assets/images/sun.jpg
    - assets/images/sun1.png
    - assets/images/crow.jpg
    - assets/images/logo.png
    - assets/images/stree.jpg
    - assets/images/stree1.jpg
    - assets/images/boss.jpg
    - assets/images/boss1.jpg
    - assets/images/trap.jpg
    - assets/images/trap1.jpg
    - assets/images/one.jpg
    - assets/images/one1.jpg
    - assets/images/glad.jpg
    - assets/images/glad1.jpg
    - assets/images/wild.jpg
    - assets/images/wild1.jpg
    - assets/images/afraid.jpg
    - assets/images/afraid1.jpg
    - assets/images/visa.png
    - assets/images/master.png
    - assets/images/payu.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"  