// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
   apiKey: "AIzaSyDAMM-uFY5_7bf7FXr9z6c8LjSEh36wV5A",
  authDomain: "cinema-9f577.firebaseapp.com",
  projectId: "cinema-9f577",
  storageBucket: "cinema-9f577.appspot.com",
  messagingSenderId: "280531577255",
  appId: "1:280531577255:web:92627349dcfeb80cebae82",
  measurementId: "G-WE8K9MYZ8W"

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWbbCxXvaieVJoda0PnayOqEkWCL_Q3CE',
    appId: '1:280531577255:android:4a5cc986bd188642ebae82',
    messagingSenderId: '280531577255',
    projectId: 'cinema-9f577',
    storageBucket: 'cinema-9f577.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyCH9pKXtk7L0kpZ0V092w7R9WkHkDfXgFQ',
  //   appId: '1:688903065578:ios:c586b2cf9534398e522c93',
  //   messagingSenderId: '688903065578',
  //   projectId: 'web1-leave',
  //   storageBucket: 'web1-leave.appspot.com',
  //   iosBundleId: 'com.example.web1',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyCH9pKXtk7L0kpZ0V092w7R9WkHkDfXgFQ',
  //   appId: '1:688903065578:ios:c586b2cf9534398e522c93',
  //   messagingSenderId: '688903065578',
  //   projectId: 'web1-leave',
  //   storageBucket: 'web1-leave.appspot.com',
  //   iosBundleId: 'com.example.web1',
  // );

  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'AIzaSyBhBm-N8sXfyS9vUZHMNQcfoqv4twMHmqc',
  //   appId: '1:688903065578:web:f6b6682f0f26b3cc522c93',
  //   messagingSenderId: '688903065578',
  //   projectId: 'web1-leave',
  //   authDomain: 'web1-leave.firebaseapp.com',
  //   storageBucket: 'web1-leave.appspot.com',
  //   measurementId: 'G-13X5YCC0RX',
  // );
}
